# EDA

In [3]:
import pandas as pd
from datasets import load_dataset

/Users/phamanhdung/Documents/msr-2027/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
artifacts = load_dataset("mvaccargiu/gitskills", "artifacts", split="train")

Downloading data: 100%|██████████| 31/31 [03:43<00:00,  7.20s/files]
Generating train split: 100%|██████████| 3797117/3797117 [00:31<00:00, 120879.04 examples/s]

In [8]:
 siblings  = load_dataset("mvaccargiu/gitskills", "artifact_siblings", split="train")

Downloading data: 100%|██████████| 45/45 [36:05<00:00, 48.12s/files]
Generating train split: 100%|██████████| 7264865/7264865 [00:42<00:00, 170329.56 examples/s]

In [9]:
repos = load_dataset("mvaccargiu/gitskills", "repos", split="train")

Generating train split: 100%|██████████| 282200/282200 [00:00<00:00, 871320.74 examples/s]

In [10]:
runs = load_dataset("mvaccargiu/gitskills", "mining_runs", split="train")

Generating train split: 100%|██████████| 7/7 [00:00<00:00, 721.04 examples/s]

In [ ]:
from pathlib import Path
from huggingface_hub import snapshot_download

# Repo layout is data/{artifacts,artifact_siblings,repos,mining_runs}/*.parquet
# Download into project root so paths become ./data/<config>/...
dest = snapshot_download(
    repo_id="mvaccargiu/gitskills",
    repo_type="dataset",
    local_dir=".",
    allow_patterns=["data/**"],
)
print("downloaded to", dest)

root = Path("data")
for p in sorted(root.iterdir()):
    if p.is_dir():
        n = len(list(p.glob("*.parquet")))
        size = sum(f.stat().st_size for f in p.rglob("*") if f.is_file())
        print(f"{p.name}: {n} parquet files, {size/1e9:.2f} GB")

In [2]:
from datasets import load_dataset

/Users/phamanhdung/Documents/msr-2027/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
artifacts = load_dataset("parquet", data_dir="data/artifacts", split="train")

In [5]:
mining_runs = load_dataset("parquet", data_dir="data/mining_runs", split="train")

In [6]:
artifacts

Dataset({
    features: ['repo_full_name', 'path', 'filename', 'location_class', 'file_sha', 'discovered_at', 'content', 'content_fetched', 'frontmatter_valid', 'name', 'description', 'body_chars', 'history_fetched', 'composition_fetched', 'dedup_primary', 'first_commit_at', 'last_commit_at', 'commit_count', 'sibling_count', 'sibling_bytes', 'has_scripts', 'has_references', 'content_sha_ok', 'composition_truncated', 'first_commit_author', 'first_commit_author_type', 'first_commit_message', 'last_commit_author', 'last_commit_author_type', 'last_commit_message'],
    num_rows: 3797117
})

In [7]:
siblings = load_dataset("parquet", data_dir="data/artifact_siblings", split="train")

In [40]:
siblings.shape

(7264865, 9)

In [10]:
df_artifacts = artifacts.shuffle(seed=0).select(range(10_000)).to_pandas()

In [11]:
df_artifacts.shape

(10000, 30)

In [10]:
df_artifacts.head()

,repo_full_name,path,filename,location_class,file_sha,discovered_at,content,content_fetched,frontmatter_valid,name,...,has_scripts,has_references,content_sha_ok,composition_truncated,first_commit_author,first_commit_author_type,first_commit_message,last_commit_author,last_commit_author_type,last_commit_message
0,InternScience/DrClaw,drclaw/agent_hub/templates/genomics/skills/com...,SKILL.md,skills-dir,23eafd0101dc530b30ac61d5bd0a707f3019a6bc,2026-07-14T18:04:23.050325+00:00,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B4san/AC-framework,framework/make_your_own/.qwen/skills/spec-clar...,SKILL.md,skills-dir,a1e028af68d2c452cca6f0ee26a40cd0c0bbbd8d,2026-07-12T06:59:13.601456+00:00,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,midudev/autoskills,packages/autoskills/skills-registry/terraform-...,SKILL.md,other,a574a0344962ae82a3bd3d9fa1fb4d4710e34f46,2026-07-20T07:38:28.581854+00:00,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NeuralBlitz/buggy,ncx/.opencode/skills/applied-systems-neuroscie...,SKILL.md,skills-dir,035c76f18cac0167fe944e7d6d87bbe41ce929ad,2026-07-09T18:07:39.150068+00:00,# Applied Systems Neuroscience Analysis Skill\...,1,0.0,NaN,...,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,DevelopersCoffee/java-cwe-security-skills,cwe-91-xml-injection/SKILL.md,SKILL.md,other,1825460684cafcfbb78c502e8a5c2c063c486a47,2026-07-09T18:07:39.150068+00:00,---\nname: cwe-91-xml-injection\ndescription: ...,1,1.0,cwe-91-xml-injection,...,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_artifacts.columns

Index(['repo_full_name', 'path', 'filename', 'location_class', 'file_sha',
       'discovered_at', 'content', 'content_fetched', 'frontmatter_valid',
       'name', 'description', 'body_chars', 'history_fetched',
       'composition_fetched', 'dedup_primary', 'first_commit_at',
       'last_commit_at', 'commit_count', 'sibling_count', 'sibling_bytes',
       'has_scripts', 'has_references', 'content_sha_ok',
       'composition_truncated', 'first_commit_author',
       'first_commit_author_type', 'first_commit_message',
       'last_commit_author', 'last_commit_author_type', 'last_commit_message'],
      dtype='str')

In [15]:
df_artifacts.dtypes

repo_full_name                  str
path                            str
filename                        str
location_class                  str
file_sha                        str
discovered_at                   str
content                         str
content_fetched               int64
frontmatter_valid           float64
name                            str
description                     str
body_chars                  float64
history_fetched               int64
composition_fetched           int64
dedup_primary                 int64
first_commit_at                 str
last_commit_at                  str
commit_count                float64
sibling_count               float64
sibling_bytes               float64
has_scripts                 float64
has_references              float64
content_sha_ok              float64
composition_truncated       float64
first_commit_author             str
first_commit_author_type        str
first_commit_message            str
last_commit_author              str
last_commit_author_type         str
last_commit_message             str
dtype: object

In [19]:
df_artifacts['file_sha'].nunique()

9701

In [11]:
df_artifacts['commit_count'].describe()

count    1162.000000
mean        2.272806
std         4.922003
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max       106.000000
Name: commit_count, dtype: float64

In [24]:
df_artifacts[df_artifacts['content'].isnull() == False]['content']

3       # Applied Systems Neuroscience Analysis Skill\...
4       ---\nname: cwe-91-xml-injection\ndescription: ...
5       ---\nname: bootstrap\nbootstrap-phase: market\...
6       # For God so loved the world, that He gave His...
7       ---\nname: shamt-validation-loop\ndescription:...
                              ...
9990    ---\nname: douyin\nversion: 1.1.0\ndescription...
9991    ---\nname: audit-design\ndescription: "Audit e...
9994    ---\nname: prompt-quality-inspector\ndescripti...
9997    ---\nname: review-perf-fix\ndescription: Revie...
9998    ---\nname: "@tank/macos-configurator"\ndescrip...
Name: content, Length: 4960, dtype: str

In [25]:
df_artifacts.shape

(10000, 30)

In [30]:
mining_runs.shape

(7, 7)

In [37]:
df_mining_runs = mining_runs.to_pandas()

In [39]:
df_mining_runs['started_at'].describe()

count                                    7
unique                                   7
top       2026-07-09T17:26:45.768703+00:00
freq                                     1
Name: started_at, dtype: object

In [41]:
df_artifacts_siblings = siblings.to_pandas()

In [42]:
df_artifacts_siblings.shape

(7264865, 9)

In [ ]:
df_artifacts_siblings.head()

,repo_full_name,artifact_path,entry_name,entry_type,entry_size,entry_sha,content,content_fetched,skipped_reason
0,0-AI-UG/cate,skills/cate-theme/SKILL.md,examples,dir,0,5f47a9bcd5bfd44a62a2c456325d84facca936a9,NaN,0,NaN
1,0-AI-UG/cate,skills/cate-theme/SKILL.md,examples/midnight-ember.cate-theme.json,file,3292,5043b7196d53053e4b1013403d3b64504e10cba1,"{\n ""version"": 1,\n ""id"": ""midnight-ember"",\...",1,NaN
2,0-AI-UG/cate,skills/cate-theme/SKILL.md,examples/paper-light.cate-theme.json,file,3384,0cb2e2103def3abbf7a717668394c233a20b1e24,"{\n ""version"": 1,\n ""id"": ""paper-light"",\n ...",1,NaN
3,0-AI-UG/cate,skills/cate-theme/SKILL.md,theme.schema.json,file,6398,f11253fd93ebee1109f0f1b9c7e44a0a97ac472e,"{\n ""$schema"": ""http://json-schema.org/draft-...",1,NaN
4,0-CYBERDYNE-SYSTEMS-0/FFT_nano,skills/runtime/fft-coder-ops/SKILL.md,references,dir,0,7e11ef515cfb17766b1e2527e3e3c291a87bb2fe,NaN,0,NaN

:

In [14]:
df_artifacts.first_commit_author_type.value_counts()

first_commit_author_type
User            981
                169
Bot              11
Organization      1
Name: count, dtype: int64

In [4]:
repos = load_dataset("parquet", data_dir="data/repos", split="train")

Generating train split: 282200 examples [00:00, 2072225.81 examples/s]

In [6]:
df_repos = repos.to_pandas()

In [7]:
df_repos.shape

(282200, 11)

In [8]:
df_repos.head()

,full_name,owner,stars,forks,is_fork,language,license,description,created_at,pushed_at,metadata_fetched
0,williamfiset/algorithms,williamfiset,18673.0,4516.0,0.0,Java,MIT,A collection of algorithms and data structures,2017-03-18T02:50:46Z,2026-06-23T09:33:06Z,1
1,alirezarezvani/claude-skills,alirezarezvani,22655.0,3150.0,0.0,Python,MIT,345 Claude Code skills & agent skills & plugin...,2025-10-19T04:04:05Z,2026-07-14T07:46:55Z,1
2,lvisei/web-developer-resources,lvisei,46.0,11.0,0.0,,MIT,A list of web full stack resources and summarize.,2018-05-31T02:05:06Z,2023-02-09T16:00:33Z,1
3,PhongFeng/FFramework,PhongFeng,97.0,29.0,0.0,C#,,Unity + AI (Harness)解决Agent可靠性与可持续性，GameFramew...,2022-08-11T07:39:41Z,2026-07-07T06:48:02Z,1
4,0xNyk/council-of-high-intelligence,0xNyk,3564.0,319.0,0.0,Shell,MIT,Structured multi-perspective deliberation for ...,2026-03-02T08:47:09Z,2026-07-15T20:09:36Z,1

In [12]:
df_repos.shape

(282200, 11)

In [13]:
# GitHub Agentic Workflows snapshots (per-collection CSVs)
from pathlib import Path

snapshot_dirs = [
    "data/2026-03-15",
    "data/2026-04-16",
    "data/2026-05-31",
    "data/2026-06-17",
    "data/2026-06-20",
    "data/2026-08-11",
]

frames = []
for d in snapshot_dirs:
    path = Path(d) / "ai_agentic_workflows.csv"
    snap = pd.read_csv(path)
    snap["ymd"] = pd.to_datetime(Path(d).name)  # folder name = collection date
    frames.append(snap)

df_aw = pd.concat(frames, ignore_index=True)
df_aw.shape, df_aw["ymd"].value_counts().sort_index()

((4688, 9),
 ymd
 2026-03-15     315
 2026-04-16     425
 2026-05-31     906
 2026-06-17    1116
 2026-06-20    1153
 2026-08-11     773
 Name: count, dtype: int64)

In [14]:
df_aw.head()

,repo,workflow_name,md_path,lock_path,md_url,lock_url,md_sha,lock_sha,ymd
0,0GiS0/github-agentic-workflows-demos,label-beautifier,.github/workflows/label-beautifier.md,.github/workflows/label-beautifier.lock.yml,https://github.com/0GiS0/github-agentic-workfl...,https://github.com/0GiS0/github-agentic-workfl...,4141d3afb0f1de3d7f6eee81610a8fc713d8283d,12c91e6631a2f810f7cfa0cd517e151ae2bda8da,2026-03-15
1,0GiS0/jsconf-2026,issue-quality-enhancer,.github/workflows/issue-quality-enhancer.md,.github/workflows/issue-quality-enhancer.lock.yml,https://github.com/0GiS0/jsconf-2026/blob/180a...,https://github.com/0GiS0/jsconf-2026/blob/180a...,467d09ae4d582a7353c7d1d7fe8a6684f8386ee0,53a54fb6c92694db5cbaf20d009881f2b1dc6bb5,2026-03-15
2,AIS-Commercial-Business-Unit/RiskInsure,HealthMonitoringAlerting.agent,.github/workflows/HealthMonitoringAlerting.age...,.github/workflows/HealthMonitoringAlerting.age...,https://github.com/AIS-Commercial-Business-Uni...,https://github.com/AIS-Commercial-Business-Uni...,b13deda7048efa88c5cf958f79980a63a77cfbb8,736d8b18e91a9ae1041ec22a2c09c300e1c5613a,2026-03-15
3,AdaCore/z3,daily-backlog-burner,.github/workflows/daily-backlog-burner.md,.github/workflows/daily-backlog-burner.lock.yml,https://github.com/AdaCore/z3/blob/24563ee6bd3...,https://github.com/AdaCore/z3/blob/24563ee6bd3...,eca1fc3417154bea2edc0e05c9e2061d9e02d23f,5dfd11104c31c8b2d9d035b0211152b11ff921e0,2026-03-15
4,AdaCore/z3,pr-fix,.github/workflows/pr-fix.md,.github/workflows/pr-fix.lock.yml,https://github.com/AdaCore/z3/blob/24563ee6bd3...,https://github.com/AdaCore/z3/blob/24563ee6bd3...,146c9eb1f72244cae8c06be13393d70020798045,2e2679e64ed5ee71c84fcda5c116a71854d56c82,2026-03-15

In [15]:
df_aw.shape

(4688, 9)

In [16]:
df_aw['repo'].nunique()

900

In [18]:
df_aw[df_aw['repo'].isin(df_repos['full_name'].unique())]['repo'].nunique()

286

In [19]:
df_repos['full_name'].nunique()

282200

## gh-aw corpus (`data/gh_aw_workflows`)

Load `ai_agentic_workflows.csv` and attach each workflow's local `.md` / `.lock.yml` text (body after the ingest header) for analysis.

In [17]:
from pathlib import Path

GH_AW_ROOT = Path("data/gh_aw_workflows")
MD_DIR = GH_AW_ROOT / "workflow-markdowns"
YML_DIR = GH_AW_ROOT / "workflow-yamls"
HEADER_SEP = "=" * 80


def _safe_stem(repo: str, workflow: str) -> str:
    return f"{repo.replace('/', '_')}_{workflow.replace('/', '_')}"


def _read_collected(path: Path) -> str | None:
    """Read a collected file; return body after the ingest header, or full text."""
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    if HEADER_SEP in text:
        return text.split(HEADER_SEP, 1)[1].lstrip("\n")
    return text


df_gh_aw = pd.read_csv(GH_AW_ROOT / "ai_agentic_workflows.csv")
stems = [_safe_stem(r, w) for r, w in zip(df_gh_aw["repo"], df_gh_aw["workflow_name"])]
df_gh_aw["md_file"] = [str(MD_DIR / f"{s}.md") for s in stems]
df_gh_aw["lock_file"] = [str(YML_DIR / f"{s}.lock.yml") for s in stems]
df_gh_aw["md_content"] = [ _read_collected(MD_DIR / f"{s}.md") for s in stems ]
df_gh_aw["lock_content"] = [ _read_collected(YML_DIR / f"{s}.lock.yml") for s in stems ]

missing_md = df_gh_aw["md_content"].isna().sum()
missing_lock = df_gh_aw["lock_content"].isna().sum()
(
    df_gh_aw.shape,
    df_gh_aw["repo"].nunique(),
    f"missing md={missing_md}",
    f"missing lock={missing_lock}",
)

((1686, 12), 324, 'missing md=0', 'missing lock=0')

In [18]:
df_gh_aw.assign(
    md_len=df_gh_aw["md_content"].fillna("").str.len(),
    lock_len=df_gh_aw["lock_content"].fillna("").str.len(),
)[["repo", "workflow_name", "md_len", "lock_len"]].head(10)

,repo,workflow_name,md_len,lock_len
0,3361559784/airi-preview,pr-triage,7818,59967
1,Activiti/activiti-cloud,supply-chain-review,19896,126953
2,Agoric/agoric-sdk,ci-doctor,8334,64249
3,Akshay20051027/C-,breaking-change-doc,3847,86977
4,Akshay20051027/C-,ci-failure-scan,31370,95018
5,Akshay20051027/C-,code-review,2351,83967
6,Akshay20051027/C-,copilot-echo,2036,82745
7,AlexBlanco21/AgenticWorkflowsComparison,classify-issues-copilot-aw,8243,72880
8,Alfresco/alfresco-build-tools,supply-chain-review,19797,127871
9,Anders-Kristiansen/proispro,daily-repo-status,1655,61405

In [19]:
df_gh_aw.head()

,repo,workflow_name,md_path,lock_path,md_url,lock_url,md_sha,lock_sha,md_file,lock_file,md_content,lock_content
0,3361559784/airi-preview,pr-triage,.github/workflows/pr-triage.md,.github/workflows/pr-triage.lock.yml,https://github.com/3361559784/airi-preview/blo...,https://github.com/3361559784/airi-preview/blo...,dc27b7ee6fad80daaf12ebedea4b7e149783502e,a4eec6f19c2daf14ede3f6415613518d0e284662,data/gh_aw_workflows/workflow-markdowns/336155...,data/gh_aw_workflows/workflow-yamls/3361559784...,---\non:\n workflow_dispatch:\n inputs:\n ...,# ___ _ _\n# / _ \ ...
1,Activiti/activiti-cloud,supply-chain-review,.github/workflows/supply-chain-review.md,.github/workflows/supply-chain-review.lock.yml,https://github.com/Activiti/activiti-cloud/blo...,https://github.com/Activiti/activiti-cloud/blo...,74a2e90d583da4e5c82cf7b98a8e52d907bab55c,05de38a4870b4518142659e4dc8c721338f03ee1,data/gh_aw_workflows/workflow-markdowns/Activi...,data/gh_aw_workflows/workflow-yamls/Activiti_a...,---\non:\n slash_command:\n name: supply-c...,"# gh-aw-metadata: {""schema_version"":""v4"",""fron..."
2,Agoric/agoric-sdk,ci-doctor,.github/workflows/ci-doctor.md,.github/workflows/ci-doctor.lock.yml,https://github.com/Agoric/agoric-sdk/blob/df5d...,https://github.com/Agoric/agoric-sdk/blob/5595...,df5d3b8b3193e07e64d020d57074135c4496623f,55951b044afccfdf9a9cd857efbdb5cbe34a0633,data/gh_aw_workflows/workflow-markdowns/Agoric...,data/gh_aw_workflows/workflow-yamls/Agoric_ago...,---\ndescription: |\n This workflow is an aut...,#\n# ___ _ _\n# / _ \...
3,Akshay20051027/C-,breaking-change-doc,.github/workflows/breaking-change-doc.md,.github/workflows/breaking-change-doc.lock.yml,https://github.com/Akshay20051027/C-/blob/8da0...,https://github.com/Akshay20051027/C-/blob/8832...,8da0dbd845c69984a9f8e717ddf4cd5fb9cb02dd,8832a724a9fd2c4668eaebeeb0a16c668bda443d,data/gh_aw_workflows/workflow-markdowns/Akshay...,data/gh_aw_workflows/workflow-yamls/Akshay2005...,---\ndescription: >\n Generate breaking chang...,"# gh-aw-metadata: {""schema_version"":""v3"",""fron..."
4,Akshay20051027/C-,ci-failure-scan,.github/workflows/ci-failure-scan.md,.github/workflows/ci-failure-scan.lock.yml,https://github.com/Akshay20051027/C-/blob/ac8f...,https://github.com/Akshay20051027/C-/blob/a951...,ac8faf5391488ed209c8fc94c5a108003b4e40b1,a95125a28233f0d59e0c6f66d1632ea8347039bd,data/gh_aw_workflows/workflow-markdowns/Akshay...,data/gh_aw_workflows/workflow-yamls/Akshay2005...,"---\nname: ""CI Outer-Loop Failure Scanner""\nde...","# gh-aw-metadata: {""schema_version"":""v3"",""fron..."

In [20]:
df_gh_aw.workflow_name.nunique()

1033

In [21]:
df_gh_aw.repo.nunique()

324

# Analyze github agentic workflow

## Task-category classification

Simple flat labels: `issue triage`, `pr review`, `documentation`, `ci repair`, ...

In [23]:
# Zero-shot task categories for gh-aw workflows
import re
from pathlib import Path

import torch
from transformers import pipeline
from tqdm.auto import tqdm

# Simple flat labels (stored in dataframe)
TASK_CATEGORIES = [
    "issue triage",
    "pr review",
    "documentation",
    "ci repair",
    "security",
    "release",
    "testing",
    "bug fix",
    "content",
    "planning",
    "monitoring",
    "other",
]

# Verbalized phrases for zero-shot NLI (short labels like "testing" confuse the model)
ZS_VERBAL = {
    "issue triage": "triaging and labeling GitHub issues",
    "pr review": "reviewing pull requests and source code",
    "documentation": "writing or updating documentation",
    "ci repair": "investigating and fixing CI or build failures",
    "security": "security, dependency, or supply chain review",
    "release": "releases, versioning, or changelogs",
    "testing": "improving test coverage or test suite quality",
    "bug fix": "implementing bug fixes in code",
    "content": "generating reports, digests, or content summaries",
    "planning": "research, planning, or specification work",
    "monitoring": "monitoring, observability, or operational alerts",
    "other": "something else",
}
ZS_LABELS = list(ZS_VERBAL.values())
ZS_TO_SIMPLE = {v: k for k, v in ZS_VERBAL.items()}

HYPOTHESIS = "This GitHub agentic workflow is primarily about {}."
ZS_MODEL = "MoritzLaurer/deberta-v3-base-zeroshot-v2.0"
MAX_CHARS = 1800


def _frontmatter_description(md: str) -> str:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", md, flags=re.S)
    if not m:
        return ""
    block = m.group(1)
    for key in ("description", "name"):
        km = re.search(rf"(?m)^{key}:\s*[\"\']?(.*?)[\"\']?\s*$", block)
        if km:
            return km.group(1).strip()
    return ""


def classify_text(row) -> str:
    name = str(row.get("workflow_name") or "")
    md = str(row.get("md_content") or "")
    desc = _frontmatter_description(md)
    body = re.sub(r"^---\s*\n.*?\n---\s*\n", "", md, count=1, flags=re.S).strip()
    parts = [f"Workflow: {name}"]
    if desc:
        parts.append(f"Description: {desc}")
    if body:
        parts.append(body[:MAX_CHARS])
    return "\n\n".join(parts)


df_task = df_gh_aw.copy()
print(f"classifying df_gh_aw: {len(df_task)} workflows")
print("categories:", TASK_CATEGORIES)

device = 0 if torch.cuda.is_available() else ("mps" if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available() else -1)
zs = pipeline(
    "zero-shot-classification",
    model=ZS_MODEL,
    device=device,
)
print(f"model={ZS_MODEL} device={device}")

classifying df_gh_aw: 1686 workflows
categories: ['issue triage', 'pr review', 'documentation', 'ci repair', 'security', 'release', 'testing', 'bug fix', 'content', 'planning', 'monitoring', 'other']

Loading weights: 100%|██████████| 202/202 [00:00<00:00, 4816.49it/s]

model=MoritzLaurer/deberta-v3-base-zeroshot-v2.0 device=mps

In [ ]:
texts = [classify_text(r) for _, r in df_task.iterrows()]

labels, scores, top3 = [], [], []
for text in tqdm(texts, desc="zero-shot"):
    out = zs(
        text,
        candidate_labels=ZS_LABELS,
        hypothesis_template=HYPOTHESIS,
        multi_label=False,
    )
    labels.append(ZS_TO_SIMPLE[out["labels"][0]])
    scores.append(float(out["scores"][0]))
    top3.append(
        {
            ZS_TO_SIMPLE[lab]: float(sc)
            for lab, sc in zip(out["labels"][:3], out["scores"][:3])
        }
    )

df_task["task_category"] = labels
df_task["task_category_score"] = scores
df_task["task_category_top3"] = top3

df_gh_aw["task_category"] = labels
df_gh_aw["task_category_score"] = scores
df_gh_aw["task_category_top3"] = top3

out_csv = Path("data/gh_aw_workflows/task_categories_zeroshot.csv")
df_task[
    ["repo", "workflow_name", "task_category", "task_category_score"]
].to_csv(out_csv, index=False)
print(f"wrote {out_csv}")
df_task["task_category"].value_counts(dropna=False)

In [ ]:
df_task[["repo", "workflow_name", "task_category", "task_category_score"]].sort_values(
    "task_category_score", ascending=False
).head(20)

## LLM classification (DeepSeek)

LiteLLM JSON mode + `deepseek-v4-flash`. Parallel requests via thread pool (`LLM_CONCURRENCY`, default 16).

Set `DEEPSEEK_API_KEY` in `.env`. Optional: `LLM_CONCURRENCY=32`.

In [24]:
# LLM task-category classifier (DeepSeek via LiteLLM)
import json
import os
import time
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from litellm import completion
from pydantic import BaseModel, Field, field_validator
from tqdm.auto import tqdm

load_dotenv("gh_data_ingestion/.env")
load_dotenv(".env")

if "TASK_CATEGORIES" not in dir():
    TASK_CATEGORIES = [
        "issue triage",
        "pr review",
        "documentation",
        "ci repair",
        "security",
        "release",
        "testing",
        "bug fix",
        "content",
        "planning",
        "monitoring",
        "other",
    ]

DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")
LLM_MAX_CHARS = 6000
LLM_PROGRESS = Path("data/gh_aw_workflows/.progress/llm_task_categories.jsonl")
LLM_OUT_CSV = Path("data/gh_aw_workflows/task_categories_llm.csv")
LLM_CONCURRENCY = int(os.getenv("LLM_CONCURRENCY", "32"))

SYSTEM_PROMPT = f"""You classify GitHub Agentic Workflows (gh-aw) by primary task.

Return exactly ONE category from this list:
{", ".join(TASK_CATEGORIES)}

Rules:
- issue triage: label/route GitHub issues
- pr review: review pull requests or code
- documentation: write/update docs
- ci repair: diagnose/fix failed CI or builds
- security: security or dependency review
- release: releases or changelogs
- testing: improve/audit tests only (not just because CI runs tests)
- bug fix: implement code fixes
- content: digests/reports/summaries
- planning: specs/research/planning
- monitoring: ops monitoring/alerts
- other: none of the above

Respond with JSON only: {{"category": "...", "confidence": 0.0, "rationale": "..."}}
"""


class WorkflowTaskLabel(BaseModel):
    category: str
    confidence: float = Field(ge=0.0, le=1.0, description="0-1 confidence")
    rationale: str = Field(max_length=300)

    @field_validator("category")
    @classmethod
    def _valid_category(cls, v: str) -> str:
        v = v.strip().lower()
        if v not in TASK_CATEGORIES:
            raise ValueError(f"category must be one of {TASK_CATEGORIES}")
        return v


def llm_input_text(row) -> str:
    if "classify_text" in dir():
        return classify_text(row)
    import re

    name = str(row.get("workflow_name") or "")
    md = str(row.get("md_content") or "")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", md, flags=re.S)
    desc = ""
    if m:
        for key in ("description", "name"):
            km = re.search(rf"(?m)^{key}:\s*[\"\']?(.*?)[\"\']?\s*$", m.group(1))
            if km:
                desc = km.group(1).strip()
                break
    body = re.sub(r"^---\s*\n.*?\n---\s*\n", "", md, count=1, flags=re.S).strip()
    parts = [f"Workflow: {name}"]
    if desc:
        parts.append(f"Description: {desc}")
    if body:
        parts.append(body[:LLM_MAX_CHARS])
    return "\n\n".join(parts)


def llm_classify_one(text: str) -> WorkflowTaskLabel:
    """JSON mode + thinking disabled (v4-flash rejects tool_choice in thinking mode)."""
    if not os.getenv("DEEPSEEK_API_KEY"):
        raise RuntimeError("Set DEEPSEEK_API_KEY in gh_data_ingestion/.env")
    resp = completion(
        model=DEEPSEEK_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        reasoning_effort="none",
        temperature=0,
        max_tokens=512,
        extra_body={"thinking": {"type": "disabled"}},
    )
    raw = resp.choices[0].message.content
    return WorkflowTaskLabel.model_validate_json(raw)


def _pair_key(repo: str, workflow: str) -> str:
    return f"{repo}::{workflow}"


def load_llm_done(path: Path) -> dict[str, dict]:
    """Load successful labels only; failed rows will be retried."""
    done: dict[str, dict] = {}
    if not path.exists():
        return done
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if not (rec.get("repo") and rec.get("workflow_name")):
                continue
            if rec.get("error") or rec.get("task_category") is None:
                continue
            done[_pair_key(rec["repo"], rec["workflow_name"])] = rec
    return done


print(f"model={DEEPSEEK_MODEL}")
print(f"categories={TASK_CATEGORIES}")
print(f"resume file={LLM_PROGRESS}")
print(f"concurrency={LLM_CONCURRENCY}")

def classify_row(row) -> dict:
    """Classify one workflow; safe to call from thread pool."""
    text = llm_input_text(row)
    try:
        label = llm_classify_one(text)
        return {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "task_category": label.category,
            "task_category_score": label.confidence,
            "task_category_rationale": label.rationale,
        }
    except Exception as exc:
        return {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "task_category": None,
            "task_category_score": None,
            "task_category_rationale": None,
            "error": str(exc),
        }

model=deepseek/deepseek-v4-flash
categories=['issue triage', 'pr review', 'documentation', 'ci repair', 'security', 'release', 'testing', 'bug fix', 'content', 'planning', 'monitoring', 'other']
resume file=data/gh_aw_workflows/.progress/llm_task_categories.jsonl
concurrency=32

In [25]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading

LLM_PROGRESS.parent.mkdir(parents=True, exist_ok=True)
done = load_llm_done(LLM_PROGRESS)

pending_rows = [
    row
    for _, row in df_gh_aw.iterrows()
    if _pair_key(row["repo"], row["workflow_name"]) not in done
]
print(f"already labeled: {len(done)} / {len(df_gh_aw)} | pending: {len(pending_rows)} | workers={LLM_CONCURRENCY}")

new_labels = 0
errors = 0
write_lock = threading.Lock()

with LLM_PROGRESS.open("a", encoding="utf-8") as prog, ThreadPoolExecutor(max_workers=LLM_CONCURRENCY) as pool:
    futures = [pool.submit(classify_row, row) for row in pending_rows]
    for fut in tqdm(as_completed(futures), total=len(futures), desc="llm classify"):
        rec = fut.result()
        pk = _pair_key(rec["repo"], rec["workflow_name"])
        with write_lock:
            prog.write(json.dumps(rec, ensure_ascii=False) + "\n")
            prog.flush()
            if rec.get("task_category"):
                done[pk] = rec
                new_labels += 1
            else:
                errors += 1

records = list(load_llm_done(LLM_PROGRESS).values())
df_llm = pd.DataFrame(records)
df_llm[["repo", "workflow_name", "task_category", "task_category_score"]].to_csv(
    LLM_OUT_CSV, index=False
)

drop_cols = [c for c in ["task_category_llm", "task_category_llm_score", "task_category_llm_rationale"] if c in df_gh_aw.columns]
df_gh_aw = df_gh_aw.drop(columns=drop_cols)
df_gh_aw = df_gh_aw.merge(
    df_llm[["repo", "workflow_name", "task_category", "task_category_score", "task_category_rationale"]].rename(
        columns={
            "task_category": "task_category_llm",
            "task_category_score": "task_category_llm_score",
            "task_category_rationale": "task_category_llm_rationale",
        }
    ),
    on=["repo", "workflow_name"],
    how="left",
)

print(f"new this run={new_labels}, errors={errors}, wrote {LLM_OUT_CSV}")
df_gh_aw["task_category_llm"].value_counts(dropna=False)

already labeled: 1280 / 1686 | pending: 406 | workers=32

llm classify: 100%|██████████| 406/406 [00:17<00:00, 23.53it/s]

new this run=242, errors=164, wrote data/gh_aw_workflows/task_categories_llm.csv

task_category_llm
content          224
pr review        196
testing          180
documentation    169
issue triage     168
NaN              164
other            127
monitoring       121
security          77
planning          73
bug fix           71
ci repair         69
release           47
Name: count, dtype: int64

In [26]:
cols = ["repo", "workflow_name", "task_category_llm", "task_category_llm_score", "task_category_llm_rationale"]
df_gh_aw[cols].sort_values("task_category_llm_score", ascending=False, na_position="last").head()

,repo,workflow_name,task_category_llm,task_category_llm_score,task_category_llm_rationale
1685,llm-d/llm-d-workload-variant-autoscaler,update-docs,documentation,1.0,The workflow is explicitly focused on updating...
374,TeplrGuy/platform-infra,ghaw-pr-review,pr review,1.0,The workflow is explicitly designed to review ...
391,Themis128/cloudless.gr,documentation-updater,documentation,1.0,The workflow's primary task is to update docum...
1108,github/gh-aw,daily-security-red-team,security,1.0,The workflow is explicitly a security red team...
387,TheLarkInn/aipm,update-docs,documentation,1.0,The workflow is explicitly focused on updating...

In [27]:
df_gh_aw['task_category_llm'].value_counts()

task_category_llm
content          224
pr review        196
testing          180
documentation    169
issue triage     168
other            127
monitoring       121
security          77
planning          73
bug fix           71
ci repair         69
release           47
Name: count, dtype: int64

# Only Issue Triage

In [28]:
df_iss_triage = df_gh_aw[df_gh_aw['task_category_llm'] == 'issue triage']

In [30]:
df_iss_triage.shape

(168, 15)

## Uses skills? (boolean) — `df_iss_triage` only

`uses_skills=True` only for **path skills**, not inline `## skill:`:

1. **Frontmatter** — non-empty `skills:` list (local paths or `owner/repo/...@sha`)
2. **Body** — instructs the agent to use a skill **file/folder** (e.g. `.agents/skills/.../SKILL.md`)

Runs only on **issue triage** rows (`df_iss_triage`). Deterministic regex first; DeepSeek LLM for ambiguous cases.

In [31]:
# Detect path-skill usage (frontmatter + body path; NOT inline ## skill:)
import json
import os
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from litellm import completion
from pydantic import BaseModel, Field
from tqdm.auto import tqdm

load_dotenv("gh_data_ingestion/.env")
load_dotenv(".env")

SKILLS_PROGRESS = Path("data/gh_aw_workflows/.progress/skills_usage_issue_triage.jsonl")
SKILLS_OUT_CSV = Path("data/gh_aw_workflows/skills_usage_issue_triage.csv")
SKILLS_CONCURRENCY = int(os.getenv("LLM_CONCURRENCY", "16"))
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)
# Path skill folders / SKILL.md (local); exclude bare "skill" words
SKILL_PATH_RE = re.compile(
    r"(?:"
    r"\.github/skills/"
    r"|\.agents/skills/"
    r"|\.claude/skills/"
    r"|\.apm/skills/"
    r"|/(?:skills)/[\w./-]+/SKILL\.md"
    r"|\bSKILL\.md\b"
    r"|skills:\s*\n\s*-\s+\S+"  # already covered by frontmatter, but ok in body
    r")",
    re.I,
)
# Instruction-like body cues near skill paths
BODY_MUST_USE_RE = re.compile(
    r"(?is)(?:read\s+and\s+follow|follow(?:\s+the)?\s+instructions?\s+in|"
    r"use\s+(?:the\s+)?|load\s+|apply\s+(?:the\s+)?|"
    r"must\s+use|according\s+to).{0,120}?"
    r"(?:\.github/skills/|\.agents/skills/|\.claude/skills/|\.apm/skills/|SKILL\.md)",
)
INLINE_SKILL_RE = re.compile(r"(?m)^#{2,3}\s*skill\s*:", re.I)
SKILL_WORD_RE = re.compile(r"\bskills?\b", re.I)


def _split_md(md: str) -> tuple[str, str]:
    md = str(md or "")
    m = FRONTMATTER_RE.match(md)
    if not m:
        return "", md
    return m.group(1), md[m.end() :]


def has_frontmatter_skills(md: str) -> bool:
    """True if YAML frontmatter has a non-empty skills: list."""
    fm, _ = _split_md(md)
    if not fm:
        return False
    # skills: [path] or skills:\n  - path
    if re.search(r"(?m)^skills\s*:\s*\[\s*\]\s*$", fm):
        return False
    if re.search(r"(?m)^skills\s*:\s*\[\s*[^\]]+\S", fm):
        return True
    m = re.search(r"(?m)^skills\s*:\s*(.*)$", fm)
    if not m:
        return False
    rest = m.group(1).strip()
    if rest and rest not in ("[]", "~", "null", "None"):
        # inline scalar / flow list
        if not rest.startswith("#"):
            return True
    # block list under skills:
    lines = fm.splitlines()
    for i, line in enumerate(lines):
        if re.match(r"^skills\s*:\s*$", line) or re.match(r"^skills\s*:\s*#", line):
            for nxt in lines[i + 1 :]:
                if re.match(r"^\S", nxt):  # next top-level key
                    break
                if re.match(r"^\s+-\s+\S+", nxt):
                    return True
            break
    return False


def has_body_skill_path(md: str) -> bool:
    """True if body clearly points at a skill file/folder (not ## skill: inline)."""
    _, body = _split_md(md)
    if not body:
        return False
    # Strip inline skill blocks so they don't count
    body_wo_inline = INLINE_SKILL_RE.split(body)[0] if INLINE_SKILL_RE.search(body) else body
    # Prefer instruction + path; else any skill-path mention in body is enough
    if BODY_MUST_USE_RE.search(body_wo_inline):
        return True
    if SKILL_PATH_RE.search(body_wo_inline):
        return True
    return False


def needs_llm_skill_check(md: str) -> bool:
    """Ambiguous: mentions skill(s) but no clear frontmatter/path hit."""
    if has_frontmatter_skills(md) or has_body_skill_path(md):
        return False
    _, body = _split_md(md)
    if INLINE_SKILL_RE.search(body) and not SKILL_PATH_RE.search(body):
        # only inline → False, no LLM needed
        return False
    return bool(SKILL_WORD_RE.search(md))


class SkillPathUsage(BaseModel):
    uses_skill_files: bool = Field(
        description="True only if the agent must use skill FILE(S)/folder paths "
        "(e.g. .github/skills/.../SKILL.md). False for inline ## skill: only, "
        "or if skills are not required."
    )
    evidence: str = Field(default="", max_length=240)


SKILL_LLM_PROMPT = """You inspect a GitHub Agentic Workflow markdown file.

Does the BODY instruct the agent to use a skill as a FILE/FOLDER path
(e.g. `.github/skills/...`, `.agents/skills/.../SKILL.md`, `owner/repo/skills/...`)?

Answer uses_skill_files=true ONLY if the agent must read/follow/load such path skills.
Answer false for:
- inline skills only (`## skill: name`)
- mentioning the word "skill" without a path
- creating/writing a new SKILL.md as the *task output* (meta), unless it also loads an existing skill path

Return JSON: {"uses_skill_files": true/false, "evidence": "short quote"}
"""


def llm_body_uses_skill_path(text: str) -> SkillPathUsage:
    if not os.getenv("DEEPSEEK_API_KEY"):
        raise RuntimeError("Set DEEPSEEK_API_KEY in .env")
    # keep prompt small
    snippet = text[:5000]
    resp = completion(
        model=DEEPSEEK_MODEL,
        messages=[
            {"role": "system", "content": SKILL_LLM_PROMPT},
            {"role": "user", "content": snippet},
        ],
        response_format={"type": "json_object"},
        reasoning_effort="none",
        temperature=0,
        max_tokens=256,
        extra_body={"thinking": {"type": "disabled"}},
    )
    return SkillPathUsage.model_validate_json(resp.choices[0].message.content)


def _pair_key(repo: str, workflow: str) -> str:
    return f"{repo}::{workflow}"


def load_skills_done(path: Path) -> dict[str, dict]:
    done: dict[str, dict] = {}
    if not path.exists():
        return done
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if rec.get("repo") and rec.get("workflow_name") and "uses_skills" in rec:
                if rec.get("error"):
                    continue
                done[_pair_key(rec["repo"], rec["workflow_name"])] = rec
    return done


print(f"model={DEEPSEEK_MODEL} concurrency={SKILLS_CONCURRENCY}")
print(f"resume={SKILLS_PROGRESS}")

model=deepseek/deepseek-v4-flash concurrency=16
resume=data/gh_aw_workflows/.progress/skills_usage_issue_triage.jsonl

In [32]:
SKILLS_PROGRESS.parent.mkdir(parents=True, exist_ok=True)
done = load_skills_done(SKILLS_PROGRESS)

rows = []
llm_pending = []

for _, row in df_iss_triage.iterrows():
    pk = _pair_key(row["repo"], row["workflow_name"])
    if pk in done:
        rows.append(done[pk])
        continue

    md = str(row.get("md_content") or "")
    fm = has_frontmatter_skills(md)
    body = has_body_skill_path(md)
    if fm or body:
        rec = {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "skills_frontmatter": fm,
            "skills_body_path": body,
            "uses_skills": True,
            "skills_detect": "frontmatter" if fm else "body_path_regex",
            "skills_evidence": "",
        }
        rows.append(rec)
    elif needs_llm_skill_check(md):
        llm_pending.append(row)
    else:
        rec = {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "skills_frontmatter": False,
            "skills_body_path": False,
            "uses_skills": False,
            "skills_detect": "none",
            "skills_evidence": "",
        }
        rows.append(rec)

print(
    f"deterministic done={len(rows)} | llm pending={len(llm_pending)} | "
    f"resumed={len(done)}"
)

write_lock = threading.Lock()
new_n = 0
err_n = 0

def _classify_skills_row(row):
    md = str(row.get("md_content") or "")
    try:
        ans = llm_body_uses_skill_path(md)
        return {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "skills_frontmatter": False,
            "skills_body_path": bool(ans.uses_skill_files),
            "uses_skills": bool(ans.uses_skill_files),
            "skills_detect": "body_path_llm",
            "skills_evidence": ans.evidence,
        }
    except Exception as exc:
        return {
            "repo": row["repo"],
            "workflow_name": row["workflow_name"],
            "skills_frontmatter": False,
            "skills_body_path": False,
            "uses_skills": False,
            "skills_detect": "error",
            "skills_evidence": "",
            "error": str(exc),
        }

with SKILLS_PROGRESS.open("a", encoding="utf-8") as prog:
    # persist deterministic rows not yet in done
    for rec in rows:
        pk = _pair_key(rec["repo"], rec["workflow_name"])
        if pk in done:
            continue
        prog.write(json.dumps(rec, ensure_ascii=False) + "\n")
        done[pk] = rec
        new_n += 1
    prog.flush()

    if llm_pending:
        with ThreadPoolExecutor(max_workers=SKILLS_CONCURRENCY) as pool:
            futs = [pool.submit(_classify_skills_row, r) for r in llm_pending]
            for fut in tqdm(as_completed(futs), total=len(futs), desc="skills llm"):
                rec = fut.result()
                pk = _pair_key(rec["repo"], rec["workflow_name"])
                with write_lock:
                    prog.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    prog.flush()
                    if rec.get("error"):
                        err_n += 1
                    else:
                        done[pk] = rec
                        rows.append(rec)
                        new_n += 1

# Prefer latest successful records
records = list(load_skills_done(SKILLS_PROGRESS).values())
df_skills = pd.DataFrame(records)
df_skills.to_csv(SKILLS_OUT_CSV, index=False)

drop_cols = [
    c
    for c in (
        "skills_frontmatter",
        "skills_body_path",
        "uses_skills",
        "skills_detect",
        "skills_evidence",
    )
    if c in df_iss_triage.columns
]
df_iss_triage = df_iss_triage.drop(columns=drop_cols)
df_iss_triage = df_iss_triage.merge(
    df_skills[
        [
            "repo",
            "workflow_name",
            "skills_frontmatter",
            "skills_body_path",
            "uses_skills",
            "skills_detect",
            "skills_evidence",
        ]
    ],
    on=["repo", "workflow_name"],
    how="left",
)
df_iss_triage["uses_skills"] = df_iss_triage["uses_skills"].fillna(False).astype(bool)
df_iss_triage["skills_frontmatter"] = df_iss_triage["skills_frontmatter"].fillna(False).astype(bool)
df_iss_triage["skills_body_path"] = df_iss_triage["skills_body_path"].fillna(False).astype(bool)

print(f"new={new_n} errors={err_n} wrote {SKILLS_OUT_CSV}")
print("uses_skills:")
print(df_iss_triage["uses_skills"].value_counts(dropna=False))
print("\nby detect:")
print(df_iss_triage["skills_detect"].value_counts(dropna=False))

deterministic done=153 | llm pending=15 | resumed=0

skills llm: 100%|██████████| 15/15 [00:02<00:00,  6.35it/s]

new=168 errors=0 wrote data/gh_aw_workflows/skills_usage_issue_triage.csv
uses_skills:
uses_skills
False    153
True      15
Name: count, dtype: int64

by detect:
skills_detect
none               142
body_path_llm       15
body_path_regex     11
Name: count, dtype: int64

In [33]:
df_iss_triage.loc[
    df_iss_triage["uses_skills"],
    ["repo", "workflow_name", "skills_frontmatter", "skills_body_path", "skills_detect", "skills_evidence"],
].head()

,repo,workflow_name,skills_frontmatter,skills_body_path,skills_detect,skills_evidence
33,DevExpGbb/zava-storefront,triage-panel,False,True,body_path_regex,
50,TeplrGuy/notifications-service,ghaw-issue-triage,False,True,body_path_regex,
51,TeplrGuy/orders-service,ghaw-issue-triage,False,True,body_path_regex,
53,TeplrGuy/platform-infra,ghaw-issue-triage,False,True,body_path_regex,
54,TeplrGuy/portal-web,ghaw-issue-triage,False,True,body_path_regex,

In [34]:
df_iss_triage.head()

,repo,workflow_name,md_path,lock_path,md_url,lock_url,md_sha,lock_sha,md_file,lock_file,md_content,lock_content,task_category_llm,task_category_llm_score,task_category_llm_rationale,skills_frontmatter,skills_body_path,uses_skills,skills_detect,skills_evidence
0,3361559784/airi-preview,pr-triage,.github/workflows/pr-triage.md,.github/workflows/pr-triage.lock.yml,https://github.com/3361559784/airi-preview/blo...,https://github.com/3361559784/airi-preview/blo...,dc27b7ee6fad80daaf12ebedea4b7e149783502e,a4eec6f19c2daf14ede3f6415613518d0e284662,data/gh_aw_workflows/workflow-markdowns/336155...,data/gh_aw_workflows/workflow-yamls/3361559784...,---\non:\n workflow_dispatch:\n inputs:\n ...,# ___ _ _\n# / _ \ ...,issue triage,0.95,The workflow's primary task is to classify pul...,False,False,False,none,
1,AlexBlanco21/AgenticWorkflowsComparison,classify-issues-copilot-aw,.github/workflows/classify-issues-copilot-aw.md,.github/workflows/classify-issues-copilot-aw.l...,https://github.com/AlexBlanco21/AgenticWorkflo...,https://github.com/AlexBlanco21/AgenticWorkflo...,af7c2e8bdf01d9998aef224e07e9aefe54f7f224,b9d7377b4c7a74630e607af1b05ffce31ab07da4,data/gh_aw_workflows/workflow-markdowns/AlexBl...,data/gh_aw_workflows/workflow-yamls/AlexBlanco...,---\ndescription: |\n Intelligent issue class...,"# gh-aw-metadata: {""schema_version"":""v3"",""fron...",issue triage,1.00,The workflow is explicitly designed to classif...,False,False,False,none,
2,Aryan-52/devsecops-ghost,linear-triage,.github/workflows/linear-triage.md,.github/workflows/linear-triage.lock.yml,https://github.com/Aryan-52/devsecops-ghost/bl...,https://github.com/Aryan-52/devsecops-ghost/bl...,1550fd8e8ceb9a64a8dbe2a90c6845f9b20add91,fb33accde8b999d03b8897b09e3f889fbcdaea65,data/gh_aw_workflows/workflow-markdowns/Aryan-...,data/gh_aw_workflows/workflow-yamls/Aryan-52_d...,---\ndescription: Triage new Linear issues for...,#\n# ___ _ _ \n# ...,issue triage,1.00,The workflow is explicitly designed to triage ...,False,False,False,none,
3,Ashesh3Projects/ralph-claude-code,triage-incoming-issues,.github/workflows/triage-incoming-issues.md,.github/workflows/triage-incoming-issues.lock.yml,https://github.com/Ashesh3Projects/ralph-claud...,https://github.com/Ashesh3Projects/ralph-claud...,668702d07fbd79fd3806c2851ba569fe6dacfcfb,eb85e4c9b7d91eb9fac219e3b89e3c68f8f7fb30,data/gh_aw_workflows/workflow-markdowns/Ashesh...,data/gh_aw_workflows/workflow-yamls/Ashesh3Pro...,---\non:\n issues:\n types: [opened]\n wo...,#\n# ___ _ _ \n# ...,issue triage,1.00,The workflow's primary task is to triage incom...,False,False,False,none,
4,Azure/AppConfiguration,issue-triage,.github/workflows/issue-triage.md,.github/workflows/issue-triage.lock.yml,https://github.com/Azure/AppConfiguration/blob...,https://github.com/Azure/AppConfiguration/blob...,58547760eee95aef8484e1e1caa523a290b96f73,5b7b8c9fc76e86618e704f2a0fdc866145b198a7,data/gh_aw_workflows/workflow-markdowns/Azure_...,data/gh_aw_workflows/workflow-yamls/Azure_AppC...,---\ndescription: Triage new issues by labelin...,#\n# ___ _ _ \n# ...,issue triage,1.00,The workflow is explicitly named 'issue-triage...,False,False,False,none,

In [35]:
df_iss_triage['uses_skills'].value_counts()

uses_skills
False    153
True      15
Name: count, dtype: int64